### ISSUE TITLE
this._tryAgainInMilliseconds Called on undefined

### ISSUE THREAD

**Issue by geekveek** [KurtWagner/checkee#1]
I've tried loading checkee on my Jenkins CLI, but it gives me this error:

```
/usr/local/share/.config/yarn/global/node_modules/checkee/lib/bitbucket/backend.js:34
                    }, this._tryAgainInMilliseconds);
                           ^
TypeError: Cannot read property '_tryAgainInMilliseconds' of undefined
    at Request.request.(anonymous function) [as _callback] (/usr/local/share/.config/yarn/global/node_modules/checkee/lib/bitbucket/backend.js:34:13)
    at Request.self.callback (/usr/local/share/.config/yarn/global/node_modules/request/request.js:186:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:191:7)
    at Request.<anonymous> (/usr/local/share/.config/yarn/global/node_modules/request/request.js:1081:10)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at IncomingMessage.<anonymous> (/usr/local/share/.config/yarn/global/node_modules/request/request.js:1001:12)
    at IncomingMessage.g (events.js:291:16)
    at emitNone (events.js:91:20)
```

**Comment by KurtWagner** [comment]
Thanks. For background that `backend.js` is the http request layer. It queues requests to avoid rate limits and on `429 Too Many Requests` it tries again in an incremental delay. I'm guessing that `this` is not the this it thinks and should really be `backend`. Once I have a failing test I will fix.
